export type TokenKind = "keyword" | "name" | "string" | "punct" | "plain";

export const TOKEN_CLASS = {
  keyword: "text-[#ff6b9d]",
  name: "text-[#b8f778]",
  string: "text-[#e8b86d]",
  punct: "text-[#d7dbe7]",
  plain: "text-white",
} as const satisfies Record<TokenKind, string>;

export const SNIPPET_TOKENS: { text: string; kind: TokenKind }[] = [
  { text: "from", kind: "keyword" },
  { text: " ", kind: "plain" },
  { text: "openai", kind: "plain" },
  { text: " ", kind: "plain" },
  { text: "import", kind: "keyword" },
  { text: " ", kind: "plain" },
  { text: "OpenAI", kind: "name" },
  { text: "\n\n", kind: "plain" },
  { text: "client", kind: "plain" },
  { text: " ", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: " ", kind: "plain" },
  { text: "OpenAI", kind: "name" },
  { text: "(", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: "    ", kind: "plain" },
  { text: "base_url", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: '"http://localhost:3227/v1"', kind: "string" },
  { text: ",", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: "    ", kind: "plain" },
  { text: "api_key", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: '"anylm-local"', kind: "string" },
  { text: ",", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: ")", kind: "punct" },
  { text: "\n\n", kind: "plain" },
  { text: "client", kind: "plain" },
  { text: ".", kind: "punct" },
  { text: "chat", kind: "name" },
  { text: ".", kind: "punct" },
  { text: "completions", kind: "name" },
  { text: ".", kind: "punct" },
  { text: "create", kind: "name" },
  { text: "(", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: "    ", kind: "plain" },
  { text: "model", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: '"llama3.2"', kind: "string" },
  { text: ",", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: "    ", kind: "plain" },
  { text: "messages", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: "[", kind: "punct" },
  { text: "{", kind: "punct" },
  { text: '"role"', kind: "string" },
  { text: ":", kind: "punct" },
  { text: " ", kind: "plain" },
  { text: '"user"', kind: "string" },
  { text: ",", kind: "punct" },
  { text: " ", kind: "plain" },
  { text: '"content"', kind: "string" },
  { text: ":", kind: "punct" },
  { text: " ", kind: "plain" },
  { text: '"ship it"', kind: "string" },
  { text: "}", kind: "punct" },
  { text: "]", kind: "punct" },
  { text: ",", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: "    ", kind: "plain" },
  { text: "stream", kind: "plain" },
  { text: "=", kind: "punct" },
  { text: "True", kind: "plain" },
  { text: ",", kind: "punct" },
  { text: "\n", kind: "plain" },
  { text: ")", kind: "punct" },
];
