// Generates src/main/env.generated.ts from app/.env before tsc runs.
//
// Why generate a source file rather than read .env at runtime: end users do
// not have a .env next to the installed app, so the values have to be present
// in the build. Generating a .ts keeps it type-checked like everything else.
//
// The generated file is gitignored and is treated as PUBLIC — see
// env-schema.js for what is allowed near it.
const fs = require("fs");
const path = require("path");
const { readEnvFile } = require("./read-env-file");
const { PUBLIC_KEYS, isForbidden } = require("./env-schema");

const appDir = path.join(__dirname, "..");
const envPath = path.join(appDir, ".env");
const outPath = path.join(appDir, "src", "main", "env.generated.ts");

function fail(message, hint) {
  console.error(`\n  build-env: ${message}`);
  if (hint) console.error(`  ${hint}`);
  console.error("");
  process.exit(1);
}

function main() {
  const fileEnv = readEnvFile(envPath);
  // Real environment variables win, so CI can inject without writing a file.
  const merged = { ...fileEnv, ...process.env };

  // 1. Refuse to continue if a secret is sitting in app/.env at all.
  const leaked = Object.keys(fileEnv).filter(isForbidden);
  if (leaked.length) {
    fail(
      `app/.env contains keys that must never ship in the app bundle: ${leaked.join(", ")}`,
      "Move server-side secrets to firebase/functions/.env, and signing/publishing credentials to CI environment variables."
    );
  }

  // 2. Warn about keys nobody reads, usually a typo.
  const unknown = Object.keys(fileEnv).filter((k) => !(k in PUBLIC_KEYS));
  for (const k of unknown) {
    console.warn(`  build-env: ignoring unknown key ${k} (not in PUBLIC_KEYS)`);
  }

  // 3. Collect the allowlisted values.
  const values = {};
  const missing = [];
  for (const [key, spec] of Object.entries(PUBLIC_KEYS)) {
    const v = merged[key];
    if (v == null || v === "") {
      if (spec.required) missing.push(key);
      continue;
    }
    values[key] = String(v);
  }

  if (missing.length) {
    fail(
      `missing required values: ${missing.join(", ")}`,
      "Copy app/.env.example to app/.env and fill it in (see firebase/README.md for where the values come from)."
    );
  }

  const body = `// GENERATED by scripts/build-env.js — do not edit, do not commit.
//
// Everything here is baked into the shipped bundle and is therefore public.
// The allowlist that decides what lands in this file lives in
// scripts/env-schema.js.
/* eslint-disable */

export const BUILD_ENV = ${JSON.stringify(values, null, 2)} as const;

export type BuildEnvKey = keyof typeof BUILD_ENV;
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, body);
  console.log(
    `  build-env: wrote ${path.relative(appDir, outPath)} (${Object.keys(values).length} public keys)`
  );
}

main();
